# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: The Goodness Guild
# Description of the Site
description:
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: hello@goodnessguild.com
facebook_username: goodnessguild
twitter_username: goodnessguild
instagram_username: goodnessguild
linkedin_username:
github_username:
youtube_channel_id: UCsMqfdfOjOsr3n-YAEO5_1g
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Dom
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: The Goodness Guild is a musical project helmed by UK-based singer-songwriter Dom Tristram. With a blend of folk, rock, and electronica, Dom weaves enchanting melodies and thought-provoking lyrics that resonate deeply.

    At the heart of The Goodness Guild's sound lies an emphasis on the power of words. Heart-felt lyrics shine through each composition, painting vivid landscapes of emotion, introspection, and social commentary.
    
    Drawing inspiration from legendary artists like , , and , The Goodness Guild creates an atmospheric soundscape that envelops listeners in a world of introspection and exploration. Deeply personal vocals, accompanied by evocative instrumentation, take the listener on a journey through the depths of the human experience. Merging the raw honesty of folk, the captivating energy of rock, and the ethereal allure of electronica results in a sonic tapestry that defies genre boundaries.

    The Goodness Guild's discography will resonate with those seeking lyrical narratives and evocative melodies. Each song is a testament to a singer-songwriter who is unconstrained by genre, capturing the essence of human emotions and experiences with unflinching honesty.
    
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
